[package]
name = "icxp"
version = "0.1.0"
authors = ["nshou <nshou@coronocoya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "icxpd"
path = "src/icxpd/icxpd.rs"

[[bin]]
name = "icxpc"
path = "src/icxpc/icxpc.rs"

[dependencies]
