version: 2.1

jobs:
  build_and_test_linux-x86_64:
    docker:
      - image: cimg/rust:1.49
    steps:
      - checkout
      - run: cargo build -vv
      - run: cargo test -vv -- --nocapture

workflows:
  linux-x86_64:
    jobs:
      - build_and_test_linux-x86_64
